### ISSUE TITLE
Correction for Macbook Pro with TouchID

### ISSUE THREAD

**Issue by FrDSimmons** [ryanmcginnis/Restart-to-Bootcamp#1]
This is a great workflow!  I needed to make two modifications to have it work with my MacBoook Pro with TouchID

set thePW to "YOURPASSWORD HERE"
set thePane to "Startup Disk"

activate application "System Preferences"
delay 1
tell application "System Events"
	tell process "System Preferences"
		click menu item thePane of menu "View" of menu bar 1
		delay 1
		if title of button 3 of window 1 is "Click the lock to make changes." then
			click button 3 of window 1
			delay 1
			_keystroke return_
			keystroke thePW
			keystroke return
			_delay 6_
			tell radio group of scroll area of group of splitter group of window 1
				click radio button 1
				# assumes Bootcamp disk is first in group, change if different
			end tell
			click button 1 of window 1
			delay 1
			keystroke return
		end if
	end tell
end tell

**Comment by ryanmcginnis** [comment]
Hey, cool! Haven't looked at this repo in a while. :) I've since bought a new MacBook, too, so I should test this out.

**Comment by gad-fly** [comment]
Hello both!

Thanks both of you so much for your work. I got this working with glee on my older laptop yesterday then after finding it wouldn't work on my touchbar laptop, was thrilled to find someone had already made a fix.

Unfortunately, it doesn't seem to be working for me :( I've been trying to get the hang of Automator in the meantime but haven't had any luck - are either of you willing to help me adjust the script so it'll work on my current laptop? (Nov '19 16" Macbook Pro with touchbar)

Best,
gad-fly

**Comment by ghost** [comment]
I ended up tweaking the script with some better timing handling (it will wait for the pane, sheet, etc. to appear vs delaying an arbitrary number of seconds) and added a section to bypass the TouchID prompt using similar principals.  Created a pull request to update the original workflow with the changes. #2

**Comment by ryanmcginnis** [comment]
nice! thanks :-)

**Comment by ghost** [comment]
This issue can be closed, I tried linking it with the merged PR but that didn't seem to work posthumously.
