### ISSUE TITLE
Doesn't work in Big Sur

### ISSUE THREAD

**Issue by krazzer** [ryanmcginnis/Restart-to-Bootcamp#4]
This script works perfect in Catalina, But it doesn't work in Big Sur anymore.

I fiddled with the AppleScript for a while, but I can't figure it out.

It seems "splitter group 1" doesn't exist anymore.

I found a script to list all the elements of the window, and I found out that the radio button has now become this:

- Scroll area
  - List
    - Group
      - Image
      - Text
      - Text
    - Group
      - Image
      - Text
      - Text

But I don't know how to trigger a click of one of the list items.

**Comment by ghost** [comment]
Yes, you are absolutely correct.  Unfortunately, I use this every day and haven't found a solution yet.  There are a couple of ways to enumerate what UI elements you can interact with.  For some reason no matter how I try it, the scroll area won't respond to "click on image" "click on text" or even rudimentary "keystroke up left left".

I'll update my latest attempt if anyone wants to fiddle with it.  It improves the error handling a little bit also.

**Comment by ghost** [comment]
FYI, the AppleScript command to see what items you can play is:

```
set winUI to entire contents of window "Startup Disk"
return winUI
```

**Comment by ghost** [comment]
The full element list follows (replace the "BOOTCAMP" and "Macintosh HD" with your labels...
```

scroll area 1
list 1 of scroll area 1
group 1 of list 1 of scroll area 1
image 1 of group 1 of list 1 of scroll area 1
static text "BOOTCAMP" of group 1 of list 1 of scroll area 1
static text "Windows" of group 1 of list 1 of scroll area 1
group 2 of list 1 of scroll area 1
image 1 of group 2 of list 1 of scroll area 1
static text "Macintosh HD" of group 2 of list 1 of scroll area 1
static text "macOS 11.0.1" of group 2 of list 1 of scroll area 1
static text 1
button "Restart…"
static text "Select the system you want to use to start up your computer"
button "Target Disk Mode…"
static text "Click to restart this computer in target disk mode"
static text "After you restart this computer in target disk mode, you can connect it to another computer using a Thunderbolt cable and use it as a hard disk."
button "Click the lock to prevent further changes."
button "Click the lock to prevent further changes."
toolbar 1
group 1 of toolbar 1
group 1 of group 1 of toolbar 1
button 1 of group 1 of group 1 of toolbar 1
button 2 of group 1 of group 1 of toolbar 1
group 2 of toolbar 1
group 1 of group 2 of toolbar 1
button "Show All" of group 1 of group 2 of toolbar 1
group 3 of toolbar 1
text field 1 of group 3 of toolbar 1
button 1 of text field 1 of group 3 of toolbar 1
button 5
button 6
button 7
static text "Startup Disk"
```

**Comment by ghost** [comment]
Using the accessibility inspector might give some clues...none of the elements in the scroll area have "Actions" assigned to them.  This might explain why "click ___" has no impact.

**Comment by ghost** [comment]
OK.  I fixed it.  It now has an external dependency on a helper app called "cliclick" which had apparently been around a few years specifically because AppleScript sucks at mouse handling.

I'll post a PR this evening.

**Comment by krazzer** [comment]
For some reason the boot drives change positions sometimes, and also sometimes it takes very long for them to show up, so I made these changes for myself:

```AppleScript
set systemOsName to "Windows" --Set the name of the OS you wish to boot to

--Wait until a bootable drive exists
repeat until exists group 1 of list 1 of scroll area 1
	delay 0.1
end repeat
		
--Find the right group to click
set systems to every group of list 1 of scroll area 1
		
repeat with system in systems
	set systemOs to value of static text 2 of system
			
	if systemOsName = systemOs then
		set systemToBootTo to system
	end if
end repeat
		
tell systemToBootTo --gets the screen coordinates of the target disk
	set p to position
	set s to size
end tell
```

**Comment by ghost** [comment]
I noticed that today also after applying the latest macOS updated to 11.1.  I'll incorporate your snippet above into PR #3

**Comment by ghost** [comment]
@krazzer's excellent selector updates added to the updates.  

@ryanmcginnis once PR #3 is merged this issue can be closed.  (In the meantime you can clone from my fork).
