### ISSUE TITLE
systemToBootTo

### ISSUE THREAD

**Issue by jcp-123** [ryanmcginnis/Restart-to-Bootcamp#5]
I am using Big Sur. The script runs but hits the following error: “The variable systemToBootTo is not defined.”

**Comment by iaur** [comment]
Editing the workflow using automator and re-invoking the ff. line fixed it on my end.

![image](https://user-images.githubusercontent.com/69610159/106385403-2601c480-640b-11eb-8252-52ebdc7df108.png)

**Comment by ryanmcginnis** [comment]
FWIW i saw another script similar to mine with fewer dependencies: https://github.com/A-Shleifman/boot2windows

thanks for your interest in this repo :)
